### ISSUE TITLE
CanvasOnChain: Create a SmartContract that stores the pixels

### ISSUE THREAD

**Issue by melanke** [BuidlGuidl/batch11.buidlguidl.com#28]
Create a contract that stores the pixel coordinate, the author of the pixel placement and the color of the pixel.

We should only have a few color options.

Remember to validate the position  of the pixel and if the color is valid.

When the contract is deployed it needs to already have a default drawing, something related to Batch11

**Comment by Abidoyesimze** [comment]
will try working on this

**Comment by Abidoyesimze** [comment]
Just raise a PR on this you can check it out and let me know if any changes are need to be made
