### ISSUE TITLE
CanvasOnChain: Show the canvas with all the pixel placements

### ISSUE THREAD

**Issue by melanke** [BuidlGuidl/batch11.buidlguidl.com#29]
Also, when the user hovers the canvas it needs to show the pixel highlight, so it's clear where is the pixel placement.

The Canvas doesn't need to be a real <canvas>, it could be anything.

(blocked by https://github.com/BuidlGuidl/batch11.buidlguidl.com/issues/28)

**Comment by Asante-ntiro** [comment]
I think it would be beneficial to add the tag: frontend to this issue
