### ISSUE TITLE
7. List the members of the batch (read BatchRegistry contract)

### ISSUE THREAD

**Issue by phipsae** [BuidlGuidl/batch11.buidlguidl.com#4]
## Goal

Show the current members of your batch in the app.

- Show it on the main page or create a page (/builders) listing all the builders registered in the BatchRegistry contract (see #10)
- Each builder should link to their personal profile (see #9)

**Comment by melanke** [comment]
Is this possible? allowList is a mapping, as far as I know it's impossible to iterate over it, right? Also, there is no event for when adding on this list.

**Comment by phipsae** [comment]
Yes exactly, you cannot iterate over a mapping in solidity. 
What event does the contract have, might this help?

**Comment by melanke** [comment]
We have the `CheckedIn` event, so it would be possible to list who made checkin. Do you think this is enough for this task?

Anyway, I will leave this issue for another builder :)

**Comment by AbolareRoheemah** [comment]
Is anyone working on this? Safe to pick it up? @phipsae @melanke

**Comment by phipsae** [comment]
Thank you for offering to take on this issue!

[gboigwe](https://github.com/gboigwe) is already working on that, see the following PR https://github.com/BuidlGuidl/batch11.buidlguidl.com/pull/20 

Perhaps you'd like to pick another issue to tackle? :)

**Comment by AbolareRoheemah** [comment]
> Thank you for offering to take on this issue!
> 
> [gboigwe](https://github.com/gboigwe) is already working on that, see the following PR #20
> 
> Perhaps you'd like to pick another issue to tackle? :)

Alright. Thanks!
