### ISSUE TITLE
5. Get the check-in count from the BatchRegistry contract

### ISSUE THREAD

**Issue by phipsae** [BuidlGuidl/batch11.buidlguidl.com#6]
## Goal

There is a "To Be implemented" string in `packages/nextjs/app/page.tsx` that should show the number of builders that have checked in to the contract.

We want to show the real count (reading from the BatchRegistry contract)

For more info about the contract: #10

**Comment by Vedant-05** [comment]
Is Someone working on this one ?

**Comment by Vedant-05** [comment]
This is only to get the Checkin Count .
So maybe it should be added to the main page tweaks only, where we are listing all the team members that checkin ?

**Comment by Vedant-05** [comment]
ok

**Comment by Vedant-05** [comment]
so this checkin counter is an open issue right ?

**Comment by Vedant-05** [comment]
Yes definately!

**Comment by Asante-ntiro** [comment]
Can I take this on? I see it's still open.

**Comment by phipsae** [comment]
Yes, go for it!
