### ISSUE TITLE
4. Tweak the main page

### ISSUE THREAD

**Issue by phipsae** [BuidlGuidl/batch11.buidlguidl.com#7]
## Goal

Discuss with your peers what you would like the homepage to show! It can be a good opportunity to tweak the app colors/layout etc.

As in #9, keep it simple (no big images, external assets, etc)

This can be an ongoing issue while you all keep implementing things.

**Comment by melanke** [comment]
Maybe we could have a grid of links to the page of each builder of the Batch.

**Comment by melanke** [comment]
> What do you mean by grid the links?

A list of links, but this list have multiple columns.

---
But actually, there's another task to build this grid: https://github.com/BuidlGuidl/batch11.buidlguidl.com/issues/4

So, maybe we could add other things on the main page as well.

**Comment by AbolareRoheemah** [comment]
Any plans for this? Is anyone working on it?

**Comment by gboigwe** [comment]
> Any plans for this? Is anyone working on it?

Yes I am working on this

**Comment by phipsae** [comment]
@AbolareRoheemah, @melanke started discussing in the TG channel what to do about it. Maybe you can collaborate together to build somehting nice.

**Comment by melanke** [comment]
@AbolareRoheemah it was just me on Telegram flooding the chat with ideas about it. Pleeeease, let's do something cool with the main page!! Do you have any idea?

Gil LB, [26/11/2024 11:35]
> Guys, I understand we can propose and implement new features for the Batch11 website, we could even create new contracts and integrate them on the website!
Anyone interested discussing about this?

> So, I take a pick on previous batch websites and some of them are pretty cool. One of them have a message wall, so anyone can send a "scrap message". We don't wanna copy their ideas, but we could use this as inspiration.

> Maybe we could have a very simple infinite turn-based game

> Like tic tac toe

> But not tic tac toe, because it only allows 2 players

> Anyone got an idea?

> Maybe we could have a board where you propose and vote for the best food dishes. Or something like that.

> It could be more "development related" but I don't like the idea of voting for the best programming language.

> We could create a coin. Batch members can claim a portion of it from time to time.

> (and we hope that, in the future, someone accepts this coin in exchange for Eth 😅)

**Comment by phipsae** [comment]
@melanke If nobody else jumps in, feel free to work on it. Maybe in between somebody joins.
