### ISSUE TITLE
3. Change the Logo / title / subtitle

### ISSUE THREAD

**Issue by phipsae** [BuidlGuidl/batch11.buidlguidl.com#8]
## Goal

Update your batch's mainpage. 

![284656861-52a77020-0c08-4136-8cc5-244bc3bd088a](https://github.com/BuidlGuidl/batch2.buidlguidl.com/assets/2486142/f9d3495a-9946-4b8e-ac55-8e00cdc380e0)

- Create a random logo (or use Dall-E!) to generate a batch logo
- title: Batch #{batch_number}
- subtitle: Whatever you feel appropriate :)

**Comment by Vedant-05** [comment]
Is this issue still open ?

**Comment by phipsae** [comment]
Yes, it is. As far as I know nobody is working on it (no PR yet, no request in here). So feel free to work on it :)

**Comment by Vedant-05** [comment]
Ok ill start working on it
